import { StyleSheet } from 'react-native';

/** Matches Profile / Owner form dark blue theme */
export const HISTORY_COLORS = {
  pageBg: '#e7f0ff',
  headerBg: '#0f213d',
  headerBgAlt: '#183b74',
  accent: '#1e3a5f',
  primary: '#2563eb',
  primaryLight: '#eff6ff',
  primaryMuted: '#eef6ff',
  white: '#FFFFFF',
  text: '#111827',
  subText: '#64748b',
  border: '#dbeafe',
  borderStrong: '#93c5fd',
  success: '#059669',
  successBg: '#ecfdf5',
  booked: '#2563eb',
  bookedBg: '#eff6ff',
  listed: '#059669',
  listedBg: '#ecfdf5',
};

const myHistoryStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: HISTORY_COLORS.pageBg,
  },
  headerSection: {
    backgroundColor: HISTORY_COLORS.headerBg,
    paddingTop: 48,
    paddingBottom: 28,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  headerTitleBlock: {
    flex: 1,
    paddingRight: 12,
  },
  filterIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterIconBtnActive: {
    backgroundColor: HISTORY_COLORS.primary,
    borderColor: '#60a5fa',
  },
  filterPanel: {
    marginTop: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  filterPanelTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#93c5fd',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
    marginLeft: 4,
  },
  filterChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  filterChipActive: {
    backgroundColor: HISTORY_COLORS.white,
    borderColor: HISTORY_COLORS.white,
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#cbd5e1',
  },
  filterChipTextActive: {
    color: HISTORY_COLORS.headerBg,
  },
  filterChipCount: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
    marginTop: 2,
  },
  filterChipCountActive: {
    color: HISTORY_COLORS.primary,
  },
  contentFilterHint: {
    fontSize: 13,
    fontWeight: '600',
    color: HISTORY_COLORS.accent,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: HISTORY_COLORS.white,
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#cbd5e1',
    lineHeight: 20,
    fontWeight: '500',
  },
  statsRow: {
    flexDirection: 'row',
    marginTop: 18,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
  },
  statValue: {
    fontSize: 22,
    fontWeight: '900',
    color: HISTORY_COLORS.white,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#93c5fd',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  listContent: {
    paddingBottom: 24,
  },
  listEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 40,
  },
  card: {
    backgroundColor: HISTORY_COLORS.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: HISTORY_COLORS.border,
    padding: 16,
    marginBottom: 14,
    shadowColor: HISTORY_COLORS.headerBg,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
    backgroundColor: HISTORY_COLORS.primaryMuted,
  },
  badgeText: {
    fontSize: 13,
    fontWeight: '700',
    color: HISTORY_COLORS.accent,
  },
  activityPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
  },
  activityPillBooked: {
    backgroundColor: HISTORY_COLORS.bookedBg,
  },
  activityPillListed: {
    backgroundColor: HISTORY_COLORS.listedBg,
  },
  activityPillText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  activityPillTextBooked: {
    color: HISTORY_COLORS.booked,
  },
  activityPillTextListed: {
    color: HISTORY_COLORS.listed,
  },
  bookingType: {
    fontSize: 12,
    fontWeight: '600',
    color: HISTORY_COLORS.primary,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: HISTORY_COLORS.headerBg,
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: HISTORY_COLORS.subText,
    marginBottom: 6,
  },
  metaLine: {
    fontSize: 12,
    color: HISTORY_COLORS.subText,
    marginBottom: 12,
    fontWeight: '500',
  },
  detailsBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: HISTORY_COLORS.border,
    backgroundColor: HISTORY_COLORS.primaryLight,
    padding: 14,
  },
  detailsTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: HISTORY_COLORS.accent,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: HISTORY_COLORS.border,
    paddingBottom: 8,
  },
  detailRow: {
    fontSize: 13,
    marginBottom: 5,
    lineHeight: 19,
    color: HISTORY_COLORS.subText,
  },
  detailValue: {
    color: HISTORY_COLORS.text,
    fontWeight: '600',
  },
  rentLine: {
    fontSize: 14,
    fontWeight: '800',
    color: HISTORY_COLORS.success,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: HISTORY_COLORS.border,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 32,
    backgroundColor: HISTORY_COLORS.white,
    marginHorizontal: 4,
    borderRadius: 20,
    paddingVertical: 36,
    borderWidth: 1,
    borderColor: HISTORY_COLORS.border,
  },
  emptyIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: HISTORY_COLORS.primaryMuted,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: HISTORY_COLORS.headerBg,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    color: HISTORY_COLORS.subText,
    marginBottom: 22,
  },
  actionBtn: {
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: HISTORY_COLORS.accent,
    shadowColor: HISTORY_COLORS.headerBg,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  actionBtnText: {
    color: HISTORY_COLORS.white,
    fontWeight: '800',
    fontSize: 15,
  },
  loader: {
    marginTop: 48,
  },
});

export default myHistoryStyles;
