import { StyleSheet } from "react-native";

/** Profile & Settings palette */
export const OWNER_COLORS = {
  pageBg: "#e7f0ff",
  headerBg: "#0f213d",
  headerBgAlt: "#183b74",
  primary: "#2563eb",
  primaryLight: "#eff6ff",
  primaryMuted: "#eef6ff",
  accent: "#1e3a5f",
  secondary: "#FF6B6B",
  text: "#111827",
  subText: "#6b7280",
  border: "#e2e8f0",
  white: "#FFFFFF",
  filledBorder: "#4ade80",
  filledBorderDark: "#34d399",
  filledBg: "#f0fdf4",
};

const ownerFormStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: OWNER_COLORS.pageBg,
  },
  headerSection: {
    backgroundColor: OWNER_COLORS.headerBg,
    paddingTop: 42,
    paddingBottom: 16,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    alignItems: "center",
  },
  stepPill: {
    backgroundColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 16,
    marginBottom: 10,
  },
  stepPillText: {
    color: "#dbeafe",
    fontSize: 12,
    fontWeight: "700",
  },
  stepProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    maxWidth: 320,
    marginTop: 4,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  stepNode: {
    alignItems: "center",
    minWidth: 52,
  },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.35)",
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  stepCircleActive: {
    borderColor: "#60a5fa",
    backgroundColor: "#2563eb",
  },
  stepCircleDone: {
    borderColor: "#60a5fa",
    backgroundColor: "#3b82f6",
  },
  stepCircleText: {
    fontSize: 14,
    fontWeight: "800",
    color: "rgba(255,255,255,0.5)",
  },
  stepCircleTextActive: {
    color: "#fff",
  },
  stepNodeLabel: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: "600",
    color: "rgba(255,255,255,0.45)",
  },
  stepNodeLabelActive: {
    color: "#fff",
    fontWeight: "800",
  },
  stepNodeLabelDone: {
    color: "#93c5fd",
  },
  stepConnector: {
    flex: 1,
    height: 3,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 2,
    marginBottom: 18,
    marginHorizontal: 4,
    minWidth: 24,
  },
  stepConnectorDone: {
    backgroundColor: "#60a5fa",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: -0.4,
    marginBottom: 4,
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#cbd5e1",
    lineHeight: 17,
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 8,
    marginBottom: 10,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
  },
  formCenterWrap: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
  },
  formActionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    width: "100%",
  },
  formActionBtn: {
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 100,
  },
  formActionBtnPrimary: {
    backgroundColor: OWNER_COLORS.accent,
  },
  formActionBtnOutline: {
    backgroundColor: OWNER_COLORS.white,
    borderWidth: 1.5,
    borderColor: "#94a3b8",
  },
  formActionBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  formActionBtnOutlineText: {
    color: "#64748b",
    fontSize: 14,
    fontWeight: "700",
  },
  mainCard: {
    backgroundColor: OWNER_COLORS.white,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
    width: "100%",
    alignSelf: "center",
  },
  cardHeader: {
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: OWNER_COLORS.headerBg,
    borderBottomWidth: 2,
    borderBottomColor: OWNER_COLORS.headerBg,
    paddingBottom: 4,
    alignSelf: "flex-start",
    marginBottom: 4,
  },
  outlinedInput: {
    fontSize: 15,
    color: OWNER_COLORS.text,
    paddingVertical: 4,
    paddingHorizontal: 0,
    margin: 0,
    minHeight: 32,
    width: "100%",
  },
  outlinedInputCompact: {
    fontSize: 14,
    minHeight: 28,
    paddingVertical: 2,
  },
  outlinedInputActive: {
    paddingTop: 2,
  },
  outlinedInputFilled: {
    color: OWNER_COLORS.headerBgAlt,
    fontWeight: "600",
    fontSize: 17,
  },
  outlinedInputDisabled: {
    color: OWNER_COLORS.subText,
    opacity: 0.85,
  },
  outlinedInputMultiline: {
    minHeight: 64,
    textAlignVertical: "top",
  },
  outlinedDimRow: {
    flexDirection: "row",
    gap: 8,
    width: "100%",
  },
  outlinedDimHalf: {
    flex: 1,
    minWidth: 0,
  },
  outlinedDimSub: {
    fontSize: 13,
    fontWeight: "600",
    color: OWNER_COLORS.subText,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 11,
    color: OWNER_COLORS.subText,
    lineHeight: 16,
    marginBottom: 8,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#f8fbff",
    marginBottom: 6,
    borderWidth: 1,
    borderColor: OWNER_COLORS.border,
  },
  fieldIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: OWNER_COLORS.primaryMuted,
    justifyContent: "center",
    alignItems: "center",
  },
  fieldContent: {
    flex: 1,
    marginLeft: 12,
  },
  fieldLabel: {
    fontSize: 11,
    color: OWNER_COLORS.subText,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "600",
  },
  fieldInput: {
    fontSize: 16,
    color: OWNER_COLORS.text,
    fontWeight: "600",
    marginTop: 4,
    paddingVertical: 2,
    paddingRight: 4,
  },
  fieldInputMultiline: {
    minHeight: 72,
    textAlignVertical: "top",
  },
  scroll: {
    width: "100%",
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
    color: OWNER_COLORS.text,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    color: OWNER_COLORS.subText,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
    width: "100%",
    fontSize: 15,
    backgroundColor: "#f8fbff",
    borderColor: OWNER_COLORS.border,
  },
  inputContainer: {
    marginBottom: 4,
    width: "100%",
  },
  row: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  halfInput: {
    flex: 1,
  },
  infoBox: {
    padding: 16,
    borderRadius: 18,
    marginBottom: 16,
    backgroundColor: OWNER_COLORS.primaryLight,
    borderWidth: 1,
    borderColor: "#dbeafe",
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 8,
    color: OWNER_COLORS.accent,
  },
  infoText: {
    fontSize: 13,
    lineHeight: 20,
    color: OWNER_COLORS.text,
  },
  sectionBlockTitle: {
    fontSize: 16,
    fontWeight: "800",
    marginTop: 4,
    marginBottom: 12,
    color: OWNER_COLORS.accent,
  },
  divider: {
    height: 1,
    backgroundColor: OWNER_COLORS.border,
    marginVertical: 16,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 62,
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: "rgba(231, 240, 255, 0.96)",
    borderTopWidth: 1,
    borderTopColor: "#dbeafe",
  },
  bottomBtn: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomBtnPrimary: {
    backgroundColor: OWNER_COLORS.accent,
    shadowColor: OWNER_COLORS.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 4,
  },
  bottomBtnOutline: {
    backgroundColor: OWNER_COLORS.white,
    borderWidth: 2,
    borderColor: "#94a3b8",
  },
  bottomBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  bottomBtnOutlineText: {
    color: "#64748b",
    fontSize: 16,
    fontWeight: "800",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  button: {
    paddingVertical: 14,
    paddingHorizontal: 22,
    borderRadius: 22,
    alignItems: "center",
    minWidth: 110,
  },
  buttonPrimary: {
    backgroundColor: OWNER_COLORS.accent,
  },
  buttonOutline: {
    backgroundColor: OWNER_COLORS.white,
    borderWidth: 2,
    borderColor: "#94a3b8",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
  },
  buttonOutlineText: {
    color: "#64748b",
    fontWeight: "800",
    fontSize: 15,
  },
  imageActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 12,
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  imageThumbWrap: {
    width: "30%",
    marginBottom: 14,
  },
  imageThumb: {
    width: "100%",
    height: 100,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: OWNER_COLORS.border,
  },
  imageRemoveBtn: {
    paddingVertical: 6,
    marginTop: 6,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: OWNER_COLORS.secondary,
  },
  imageRemoveText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  imageAddBox: {
    height: 100,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: OWNER_COLORS.primary,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: OWNER_COLORS.primaryLight,
  },
  imageAddPlus: {
    fontSize: 28,
    color: OWNER_COLORS.primary,
  },
  imageAddLabel: {
    fontSize: 11,
    color: OWNER_COLORS.subText,
    marginTop: 2,
  },
  imageCount: {
    textAlign: "center",
    marginTop: 8,
    fontSize: 13,
    fontWeight: "700",
    color: OWNER_COLORS.subText,
  },
  itemCard: {
    borderWidth: 1,
    borderColor: "#dbeafe",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    backgroundColor: "#f8fbff",
  },
  itemCardTitle: {
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 14,
    textAlign: "center",
    color: OWNER_COLORS.accent,
  },
  pricingCard: {
    borderWidth: 1,
    borderColor: "#dbeafe",
    borderRadius: 18,
    padding: 14,
    marginTop: 12,
    backgroundColor: OWNER_COLORS.white,
  },
  pricingHeading: {
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 10,
    color: OWNER_COLORS.accent,
  },
  twoColumn: {
    flexDirection: "row",
    width: "100%",
  },
  column: {
    flex: 1,
    padding: 6,
  },
  columnHeading: {
    textAlign: "center",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 8,
    color: OWNER_COLORS.accent,
  },
  verticalDivider: {
    width: 2,
    backgroundColor: "#dbeafe",
    borderRadius: 1,
  },
  radioRow: {
    flexDirection: "row",
    gap: 12,
    marginVertical: 8,
  },
  radio: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderRadius: 14,
    borderColor: OWNER_COLORS.border,
    backgroundColor: "#f8fbff",
  },
  radioActive: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderRadius: 14,
    borderColor: OWNER_COLORS.accent,
    backgroundColor: OWNER_COLORS.primaryLight,
  },
  addItemButton: {
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: "center",
    marginVertical: 10,
    backgroundColor: OWNER_COLORS.accent,
  },
  addItemButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  removeItemButton: {
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
    marginTop: 10,
    backgroundColor: OWNER_COLORS.secondary,
  },
  removeItemButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
  areaRow: {
    flexDirection: "row",
    gap: 12,
  },
  areaHalf: {
    flex: 1,
  },
  restroomRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
    marginTop: 8,
    marginBottom: 8,
  },
  restroomOption: {
    flexDirection: "row",
    alignItems: "center",
  },
  restroomOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: OWNER_COLORS.border,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  restroomInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: OWNER_COLORS.accent,
  },
  restroomLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: OWNER_COLORS.text,
  },
});

export const getOwnerFormThemeColors = (dark = false) => ({
  primary: OWNER_COLORS.primary,
  text: dark ? "#f3f4f6" : OWNER_COLORS.text,
  subText: dark ? "#9ca3af" : OWNER_COLORS.subText,
  card: dark ? "#1f2937" : OWNER_COLORS.white,
  border: dark ? "#374151" : OWNER_COLORS.border,
  placeholder: dark ? "#6b7280" : "#94a3b8",
  secondary: OWNER_COLORS.secondary,
});

export const getOwnerFormStyles = (_colors = {}, dark = false) => {
  const themeColors = getOwnerFormThemeColors(dark);
  const text = themeColors.text;
  const subText = themeColors.subText;
  const cardBg = themeColors.card;
  const screenBg = dark ? "#111827" : OWNER_COLORS.pageBg;
  const border = themeColors.border;
  const placeholder = themeColors.placeholder;
  const accent = OWNER_COLORS.accent;

  return {
    themeColors,
    colors: { primary: themeColors.primary, text, subText, cardBg, screenBg, border, placeholder },
    screen: [ownerFormStyles.screen, { backgroundColor: screenBg }],
    scrollContent: ownerFormStyles.scrollContent,
    scroll: ownerFormStyles.scroll,
    headerSection: [
      ownerFormStyles.headerSection,
      { backgroundColor: dark ? OWNER_COLORS.headerBg : OWNER_COLORS.headerBg },
    ],
    headerTitle: ownerFormStyles.headerTitle,
    headerSubtitle: ownerFormStyles.headerSubtitle,
    stepPill: ownerFormStyles.stepPill,
    stepPillText: ownerFormStyles.stepPillText,
    stepProgressRow: ownerFormStyles.stepProgressRow,
    stepNode: ownerFormStyles.stepNode,
    stepCircle: ownerFormStyles.stepCircle,
    stepCircleActive: ownerFormStyles.stepCircleActive,
    stepCircleDone: ownerFormStyles.stepCircleDone,
    stepCircleText: ownerFormStyles.stepCircleText,
    stepCircleTextActive: ownerFormStyles.stepCircleTextActive,
    stepNodeLabel: ownerFormStyles.stepNodeLabel,
    stepNodeLabelActive: ownerFormStyles.stepNodeLabelActive,
    stepNodeLabelDone: ownerFormStyles.stepNodeLabelDone,
    stepConnector: ownerFormStyles.stepConnector,
    stepConnectorDone: ownerFormStyles.stepConnectorDone,
    formCenterWrap: ownerFormStyles.formCenterWrap,
    formActionsRow: ownerFormStyles.formActionsRow,
    formActionBtn: ownerFormStyles.formActionBtn,
    formActionBtnPrimary: ownerFormStyles.formActionBtnPrimary,
    formActionBtnOutline: ownerFormStyles.formActionBtnOutline,
    formActionBtnText: ownerFormStyles.formActionBtnText,
    formActionBtnOutlineText: ownerFormStyles.formActionBtnOutlineText,
    mainCard: [ownerFormStyles.mainCard, { backgroundColor: cardBg }],
    cardHeader: ownerFormStyles.cardHeader,
    sectionTitle: [
      ownerFormStyles.sectionTitle,
      { color: OWNER_COLORS.headerBg, borderBottomColor: OWNER_COLORS.headerBg },
    ],
    sectionSubtitle: [ownerFormStyles.sectionSubtitle, { color: subText }],
    fieldRow: [
      ownerFormStyles.fieldRow,
      { backgroundColor: dark ? "#1f2937" : "#f8fbff", borderColor: border },
    ],
    fieldIconBox: [
      ownerFormStyles.fieldIconBox,
      { backgroundColor: dark ? "#374151" : OWNER_COLORS.primaryMuted },
    ],
    fieldContent: ownerFormStyles.fieldContent,
    fieldLabel: [ownerFormStyles.fieldLabel, { color: subText }],
    fieldInput: [ownerFormStyles.fieldInput, { color: text }],
    fieldInputMultiline: ownerFormStyles.fieldInputMultiline,
    outlinedInput: [ownerFormStyles.outlinedInput, { color: text }],
    outlinedInputCompact: ownerFormStyles.outlinedInputCompact,
    outlinedInputFilled: ownerFormStyles.outlinedInputFilled,
    outlinedInputActive: ownerFormStyles.outlinedInputActive,
    outlinedInputDisabled: ownerFormStyles.outlinedInputDisabled,
    outlinedInputMultiline: ownerFormStyles.outlinedInputMultiline,
    outlinedDimRow: ownerFormStyles.outlinedDimRow,
    outlinedDimHalf: ownerFormStyles.outlinedDimHalf,
    outlinedDimSub: [ownerFormStyles.outlinedDimSub, { color: subText }],
    label: [ownerFormStyles.label, { color: text }],
    subLabel: [ownerFormStyles.subLabel, { color: subText }],
    input: [
      ownerFormStyles.input,
      {
        backgroundColor: dark ? "#374151" : "#f8fbff",
        color: text,
        borderColor: border,
      },
    ],
    inputDisabled: [
      ownerFormStyles.input,
      { backgroundColor: dark ? "#1f2937" : "#f1f5f9", color: subText, borderColor: border },
    ],
    inputContainer: ownerFormStyles.inputContainer,
    row: ownerFormStyles.row,
    halfInput: ownerFormStyles.halfInput,
    infoBox: [
      ownerFormStyles.infoBox,
      {
        backgroundColor: dark ? "#1e3a5f" : OWNER_COLORS.primaryLight,
        borderColor: dark ? "#2563eb" : "#dbeafe",
      },
    ],
    infoTitle: [ownerFormStyles.infoTitle, { color: accent }],
    infoText: [ownerFormStyles.infoText, { color: text }],
    sectionBlockTitle: [ownerFormStyles.sectionBlockTitle, { color: accent }],
    divider: [ownerFormStyles.divider, { backgroundColor: border }],
    bottomBar: [
      ownerFormStyles.bottomBar,
      {
        backgroundColor: dark ? "rgba(17,24,39,0.96)" : "rgba(231, 240, 255, 0.96)",
        borderTopColor: dark ? "#374151" : "#dbeafe",
      },
    ],
    bottomBtn: ownerFormStyles.bottomBtn,
    bottomBtnPrimary: ownerFormStyles.bottomBtnPrimary,
    bottomBtnOutline: ownerFormStyles.bottomBtnOutline,
    bottomBtnText: ownerFormStyles.bottomBtnText,
    bottomBtnOutlineText: ownerFormStyles.bottomBtnOutlineText,
    buttonRow: ownerFormStyles.buttonRow,
    button: ownerFormStyles.button,
    buttonPrimary: [ownerFormStyles.button, ownerFormStyles.buttonPrimary],
    buttonOutline: ownerFormStyles.buttonOutline,
    buttonText: ownerFormStyles.buttonText,
    buttonOutlineText: ownerFormStyles.buttonOutlineText,
    imageActionsRow: ownerFormStyles.imageActionsRow,
    imageGrid: ownerFormStyles.imageGrid,
    imageThumbWrap: ownerFormStyles.imageThumbWrap,
    imageThumb: [ownerFormStyles.imageThumb, { borderColor: border }],
    imageRemoveBtn: ownerFormStyles.imageRemoveBtn,
    imageRemoveText: ownerFormStyles.imageRemoveText,
    imageAddBox: [
      ownerFormStyles.imageAddBox,
      {
        borderColor: themeColors.primary,
        backgroundColor: dark ? "#374151" : OWNER_COLORS.primaryLight,
      },
    ],
    imageAddPlus: [ownerFormStyles.imageAddPlus, { color: themeColors.primary }],
    imageAddLabel: [ownerFormStyles.imageAddLabel, { color: subText }],
    imageCount: [ownerFormStyles.imageCount, { color: subText }],
    itemCard: [
      ownerFormStyles.itemCard,
      {
        backgroundColor: dark ? "#1f2937" : "#f8fbff",
        borderColor: dark ? "#374151" : "#dbeafe",
      },
    ],
    itemCardTitle: [ownerFormStyles.itemCardTitle, { color: accent }],
    pricingCard: [
      ownerFormStyles.pricingCard,
      { backgroundColor: cardBg, borderColor: dark ? "#374151" : "#dbeafe" },
    ],
    pricingHeading: [ownerFormStyles.pricingHeading, { color: accent }],
    twoColumn: ownerFormStyles.twoColumn,
    column: ownerFormStyles.column,
    columnHeading: [ownerFormStyles.columnHeading, { color: accent }],
    verticalDivider: ownerFormStyles.verticalDivider,
    radioRow: ownerFormStyles.radioRow,
    radio: [ownerFormStyles.radio, { borderColor: border, backgroundColor: dark ? "#374151" : "#f8fbff" }],
    radioActive: [
      ownerFormStyles.radioActive,
      { borderColor: accent, backgroundColor: dark ? "#1e3a5f" : OWNER_COLORS.primaryLight },
    ],
    radioText: { color: text, fontWeight: "600" },
    radioTextActive: { color: accent, fontWeight: "800" },
    addItemButton: ownerFormStyles.addItemButton,
    addItemButtonText: ownerFormStyles.addItemButtonText,
    removeItemButton: ownerFormStyles.removeItemButton,
    removeItemButtonText: ownerFormStyles.removeItemButtonText,
    areaRow: ownerFormStyles.areaRow,
    areaHalf: ownerFormStyles.areaHalf,
    restroomRow: ownerFormStyles.restroomRow,
    restroomOption: ownerFormStyles.restroomOption,
    restroomOuter: [ownerFormStyles.restroomOuter, { borderColor: border }],
    restroomOuterSelected: [ownerFormStyles.restroomOuter, { borderColor: accent }],
    restroomInner: ownerFormStyles.restroomInner,
    restroomLabel: [ownerFormStyles.restroomLabel, { color: text }],
    // legacy aliases
    card: [ownerFormStyles.mainCard, { backgroundColor: cardBg }],
    title: [ownerFormStyles.sectionTitle, { color: text }],
    subtitle: [ownerFormStyles.sectionSubtitle, { color: subText }],
    content: ownerFormStyles.scrollContent,
  };
};

export default ownerFormStyles;
