import { StyleSheet } from 'react-native';

const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0',
  },
  headerSection: {
    backgroundColor: '#1e3a5f',
    paddingTop: 50,
    paddingBottom: 40,
    paddingHorizontal: 30,
    alignItems: 'flex-start',
    borderBottomLeftRadius: 45,
    borderBottomRightRadius: 45,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: -0.5,
  },
  scrollContent: {
    paddingBottom: 20,
    marginTop: -20,
  },
  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 30,
    marginHorizontal: 20,
    padding: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 15,
  },
  avatarContainer: {
    borderRadius: 60,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: '#1e3a5f',
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E8F0FE',
  },
  editBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1e3a5f',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
    zIndex: 2,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  userName: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1a1a1a',
    marginBottom: 5,
  },
  userEmail: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
  },
  editProfileBtn: {
    backgroundColor: '#1e3a5f',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
    shadowColor: '#1e3a5f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  editProfileBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  infoSection: {
    backgroundColor: '#fff',
    borderRadius: 25,
    marginHorizontal: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1a1a1a',
    marginBottom: 25,
    borderBottomWidth: 3,
    borderBottomColor: '#1e3a5f',
    paddingBottom: 8,
    width: 200,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 22,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  infoTextContainer: {
    marginLeft: 15,
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: 17,
    color: '#1a1a1a',
    marginTop: 3,
    fontWeight: '600',
  },
  editInput: {
    fontSize: 17,
    color: '#1a1a1a',
    marginTop: 3,
    fontWeight: '600',
    borderBottomWidth: 2,
    borderBottomColor: '#1e3a5f',
    paddingVertical: 3,
  },
  editButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginHorizontal: 20,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: '#1e3a5f',
    shadowColor: '#1e3a5f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
  },
  cancelEditButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#6c757d',
    backgroundColor: '#fff',
  },
  cancelEditButtonText: {
    color: '#6c757d',
    fontSize: 17,
    fontWeight: 'bold',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingVertical: 16,
    marginHorizontal: 20,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#dc3545',
    backgroundColor: '#fff',
  },
  logoutButtonText: {
    color: '#dc3545',
    fontSize: 17,
    fontWeight: 'bold',
    marginLeft: 10,
  },
});

export default profileStyles;
