import { StyleSheet } from 'react-native';

const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e7f0ff',
  },
  headerSection: {
    backgroundColor: '#0f213d',
    paddingTop: 55,
    paddingBottom: 45,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 38,
    borderBottomRightRadius: 38,
  },
  headerTop: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: -0.6,
  },
  headerSubtitle: {
    fontSize: 15,
    color: '#cbd5e1',
    lineHeight: 22,
    width: '80%',
  },
  headerIconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    paddingBottom: 24,
    marginTop: -28,
  },
  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 30,
    marginHorizontal: 20,
    padding: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 15,
  },
  avatarContainer: {
    borderRadius: 60,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: '#1e3a5f',
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E8F0FE',
  },
  editBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1e3a5f',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
    zIndex: 2,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  userName: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1a1a1a',
    marginBottom: 5,
  },
  userEmail: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
  },
  editProfileBtn: {
    backgroundColor: '#1e3a5f',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
    shadowColor: '#1e3a5f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  editProfileBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  infoSection: {
    backgroundColor: '#fff',
    borderRadius: 28,
    marginHorizontal: 20,
    paddingVertical: 20,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 18,
    borderBottomWidth: 3,
    borderBottomColor: '#2563eb',
    paddingBottom: 8,
    width: 170,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#f8fbff',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  infoTextContainer: {
    marginLeft: 14,
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  infoValue: {
    fontSize: 17,
    color: '#111827',
    marginTop: 4,
    fontWeight: '700',
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: '#eef6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editInput: {
    fontSize: 17,
    color: '#111827',
    marginTop: 4,
    fontWeight: '700',
    borderBottomWidth: 2,
    borderBottomColor: '#2563eb',
    paddingVertical: 4,
  },
  editButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginHorizontal: 20,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: '#1e3a5f',
    shadowColor: '#1e3a5f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
  },
  cancelEditButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 22,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#6c757d',
    backgroundColor: '#fff',
  },
  cancelEditButtonText: {
    color: '#6c757d',
    fontSize: 17,
    fontWeight: 'bold',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingVertical: 16,
    marginHorizontal: 20,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#dc3545',
    backgroundColor: '#fff',
  },
  logoutButtonText: {
    color: '#dc3545',
    fontSize: 17,
    fontWeight: 'bold',
    marginLeft: 10,
  },
});

export default profileStyles;
