import { StyleSheet } from "react-native";
import { OWNER_COLORS } from "../ownerFormStyles";

export const ADMIN_COLORS = {
  pageBg: OWNER_COLORS.pageBg,
  headerBg: OWNER_COLORS.headerBg,
  headerBgAlt: OWNER_COLORS.headerBgAlt,
  primary: OWNER_COLORS.primary,
  accent: OWNER_COLORS.accent,
  text: OWNER_COLORS.text,
  subText: OWNER_COLORS.subText,
  white: OWNER_COLORS.white,
  border: "#dbeafe",
  cardBorder: "#dbeafe",
  success: "#059669",
  danger: "#dc2626",
};

const C = ADMIN_COLORS;

const adminStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: C.pageBg,
  },
  screenCentered: {
    flexGrow: 1,
    backgroundColor: C.pageBg,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
    width: "100%",
  },
  pageHeader: {
    backgroundColor: C.headerBg,
    paddingTop: 48,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    width: "100%",
  },
  pageHeaderTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: -0.4,
  },
  pageHeaderSubtitle: {
    fontSize: 14,
    color: "#cbd5e1",
    marginTop: 6,
    fontWeight: "500",
    lineHeight: 20,
  },
  body: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    width: "100%",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: C.headerBg,
    marginBottom: 16,
    textAlign: "center",
  },
  loadingWrap: {
    marginTop: 48,
    alignItems: "center",
  },
  noDataText: {
    fontSize: 16,
    color: C.subText,
    marginTop: 40,
    textAlign: "center",
    fontWeight: "600",
  },
  card: {
    backgroundColor: C.white,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: C.cardBorder,
    shadowColor: "#0f213d",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  highlightCard: {
    borderColor: C.primary,
    borderWidth: 2,
    backgroundColor: "#f8fbff",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingBottom: 12,
    marginBottom: 12,
    gap: 8,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: C.headerBg,
  },
  cardSubtitle: {
    fontSize: 13,
    color: C.subText,
    marginTop: 4,
    fontWeight: "600",
  },
  cardSection: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: C.accent,
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  detailRow: {
    flexDirection: "row",
    marginBottom: 6,
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: C.subText,
    width: 110,
  },
  detailValue: {
    fontSize: 14,
    color: C.text,
    flex: 1,
    fontWeight: "500",
  },
  noPropertyText: {
    fontSize: 14,
    color: C.subText,
    fontStyle: "italic",
  },
  viewPropertyBtn: {
    backgroundColor: C.accent,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 4,
  },
  viewPropertyBtnDisabled: {
    backgroundColor: "#94a3b8",
  },
  viewPropertyBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
  buttonsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    width: "100%",
    maxWidth: 520,
    gap: 10,
  },
  dashboardButton: {
    backgroundColor: C.accent,
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 16,
    width: "47%",
    alignItems: "center",
    minHeight: 56,
    justifyContent: "center",
    shadowColor: "#0f213d",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  logoutButton: {
    backgroundColor: C.danger,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
    marginTop: 24,
  },
  btnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  input: {
    width: "100%",
    maxWidth: 400,
    height: 50,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 16,
    color: C.text,
  },
  button: {
    backgroundColor: C.accent,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 14,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
    marginBottom: 12,
  },
  cancelButton: {
    backgroundColor: "#64748b",
  },
  signupCard: {
    backgroundColor: C.white,
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    width: "100%",
    borderLeftWidth: 4,
    borderLeftColor: C.accent,
    borderWidth: 1,
    borderColor: C.cardBorder,
  },
  signupName: {
    fontSize: 17,
    fontWeight: "800",
    color: C.headerBg,
    marginBottom: 6,
  },
  signupLine: {
    fontSize: 14,
    color: C.text,
    marginBottom: 3,
  },
  signupMeta: {
    fontSize: 13,
    color: C.subText,
    marginTop: 4,
  },
  // Legacy aliases
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: C.pageBg,
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 24,
    color: C.headerBg,
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: C.pageBg,
  },
  dashboardContainerCentered: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: C.pageBg,
    padding: 20,
    minHeight: "100%",
  },
  dashboardContentContainer: {
    alignItems: "center",
    width: "100%",
    maxWidth: 640,
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  dashboardScrollCentered: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  dashboardTitle: {
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 8,
    color: C.headerBg,
    textAlign: "center",
  },
  dashboardContent: {
    fontSize: 16,
    marginBottom: 20,
    color: C.subText,
    textAlign: "center",
  },
});

export default adminStyles;
