import { StyleSheet } from "react-native";
import { ADMIN_COLORS } from "./adminStyles";

const C = ADMIN_COLORS;

const residentialOwnerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.pageBg,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    minHeight: 0,
  },
  title: {
    fontSize: 20,
    fontWeight: "900",
    color: C.headerBg,
    textAlign: "center",
    marginBottom: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: C.subText,
    fontWeight: "600",
  },
  noDataContainer: {
    paddingVertical: 40,
    alignItems: "center",
  },
  noDataText: {
    fontSize: 16,
    color: C.subText,
    textAlign: "center",
    fontWeight: "600",
  },
  ownerCard: {
    backgroundColor: C.white,
    padding: 16,
    marginBottom: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.cardBorder,
    shadowColor: "#0f213d",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  summaryContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  summaryLeft: {
    flex: 1,
  },
  ownerName: {
    fontSize: 18,
    fontWeight: "900",
    color: C.headerBg,
    marginBottom: 6,
  },
  summaryText: {
    fontSize: 14,
    color: C.subText,
    marginBottom: 4,
    fontWeight: "500",
  },
  viewMoreButton: {
    backgroundColor: C.accent,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    minWidth: 88,
    alignItems: "center",
  },
  viewMoreText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  collapseButtonRow: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    width: "100%",
  },
  collapseButton: {
    backgroundColor: "#64748b",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: "center",
    width: "100%",
  },
  collapseButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
  },
  detailedContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  detailSection: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: "#f8fbff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: C.headerBg,
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: C.headerBg,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  detailText: {
    fontSize: 14,
    color: C.text,
    marginBottom: 6,
    lineHeight: 20,
  },
  detailLabel: {
    fontWeight: "700",
    color: C.accent,
  },
  detailValue: {
    color: C.text,
    fontWeight: "500",
  },
  conditionText: {
    fontSize: 14,
    color: C.text,
    fontWeight: "500",
    lineHeight: 22,
    marginBottom: 6,
  },
  updateButtonContainer: {
    marginTop: 10,
    alignItems: "flex-end",
  },
  updateButton: {
    backgroundColor: C.success,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 14,
    minWidth: 120,
    alignItems: "center",
  },
  updateButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 33, 61, 0.55)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "90%",
    maxHeight: "80%",
    backgroundColor: C.white,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: C.cardBorder,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: C.headerBg,
    marginBottom: 6,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    color: C.subText,
    marginBottom: 16,
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 14,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: C.accent,
    marginBottom: 8,
  },
  formInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    backgroundColor: "#f8fbff",
    color: C.text,
  },
  inlineInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inlineInputWrapper: {
    flex: 1,
  },
  inlineInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    backgroundColor: "#f8fbff",
  },
  separator: {
    fontSize: 18,
    fontWeight: "bold",
    color: C.subText,
    marginHorizontal: 10,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    backgroundColor: "#f8fbff",
    overflow: "hidden",
  },
  picker: {
    height: 50,
    width: "100%",
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    gap: 10,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: "#64748b",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  modalCancelButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
  },
  modalSubmitButton: {
    flex: 1,
    backgroundColor: C.accent,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  modalSubmitButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
  },
});

export default residentialOwnerStyles;
